:

Модули управления пакетами:

apt: для управления пакетами в системах на базе Debian (например, Ubuntu).
yum: для управления пакетами в системах на базе Red Hat (например, CentOS, Fedora).
dnf: для управления пакетами в более новых версиях Red Hat и Fedora.
package: обобщенный модуль для работы с пакетными менеджерами различных систем.
Модули управления файлами:

copy: для копирования файлов на удаленные хосты.
template: для создания файлов из шаблонов Jinja2 и копирования их на удаленные хосты.
file: для управления атрибутами файлов и директорий (например, права доступа, владельцы).
fetch: для копирования файлов с удаленных хостов на локальную машину.
lineinfile: для управления отдельными строками в файлах.
Модули управления пользователями и группами:

user: для управления пользователями.
group: для управления группами.
Модули управления сервисами:

service: для управления системными службами (запуск, остановка, перезапуск, включение в автозагрузку и т.д.).
systemd: для управления службами, использующими systemd.
Модули управления сетью:

firewalld: для управления настройками брандмауэра в системах, использующих firewalld.
ufw: для управления настройками брандмауэра в системах, использующих UFW.
Модули управления базами данных:

mysql_db, mysql_user: для управления базами данных MySQL.
postgresql_db, postgresql_user: для управления базами данных PostgreSQL.
Модули работы с облачными провайдерами:

ec2, ec2_instance: для управления ресурсами в AWS.
gcp_compute_instance: для управления ресурсами в Google Cloud Platform.
azure_rm: для управления ресурсами в Microsoft Azure.
Модули управления конфигурацией системы:

hostname: для управления именами хостов.
sysctl: для управления параметрами sysctl.
timezone: для управления настройками временной зоны.
Модули контроля версий:

git: для управления репозиториями Git.
svn: для управления репозиториями Subversion.
Модули для выполнения команд:

command: для выполнения команд на удаленных хостах.
shell: для выполнения команд в оболочке на удаленных хостах.
raw: для выполнения команд напрямую без использования Python на удаленных хостах.