Роли
Роли (roles) в Ansible представляют собой более структурированный и модульный способ организации плейбуков. Роли позволяют организовать задачи, переменные, файлы, шаблоны и другие компоненты в отдельные, переиспользуемые блоки. Это делает код более организованным и облегчают его поддержку и масштабирование.

Роли имеют определенную структуру директорий:

css
Копировать код
roles/
  my_role/
    tasks/
      main.yml
    handlers/
      main.yml
    templates/
    files/
    vars/
      main.yml
    defaults/
      main.yml
    meta/
      main.yml

  
Шаг 1: Создание структуры ролей
Создайте следующую структуру директорий для вашей роли:

css
Копировать код
roles/
  apache/
    tasks/
      main.yml
    handlers/
      main.yml
    templates/
      apache2.conf.j2
    files/
    vars/
      main.yml
    defaults/
      main.yml
    meta/
      main.yml
Шаг 2: Определение задач (tasks)
Файл roles/apache/tasks/main.yml будет содержать задачи для установки и настройки Apache:

---
- name: Установка Apache
  apt:
    name: apache2
    state: present
  become: yes

- name: Копирование конфигурационного файла Apache
  template:
    src: apache2.conf.j2
    dest: /etc/apache2/apache2.conf
  notify: Перезапуск Apache

- name: Обеспечение запуска Apache при старте системы
  service:
    name: apache2
    enabled: yes
    state: started
  become: yes
Шаг 3: Определение обработчиков (handlers)
Файл roles/apache/handlers/main.yml будет содержать обработчики для перезапуска Apache:

---
- name: Перезапуск Apache
  service:
    name: apache2
    state: restarted
  become: yes
Шаг 4: Создание шаблона конфигурационного файла
Файл roles/apache/templates/apache2.conf.j2 будет содержать шаблон конфигурационного файла Apache. Это пример минимального шаблона:

j2
# This is a basic Apache configuration file
ServerName {{ ansible_hostname }}

# Other configurations can be added here
Шаг 5: Определение переменных (vars)
Файл roles/apache/vars/main.yml может содержать переменные, специфичные для этой роли:


---
# Переменные, используемые в роли
apache_server_name: "{{ ansible_hostname }}"
Шаг 6: Определение значений по умолчанию (defaults)
Файл roles/apache/defaults/main.yml будет содержать значения по умолчанию для переменных:


---
# Значения переменных по умолчанию
apache_server_name: "localhost"
Шаг 7: Определение метаданных (meta)
Файл roles/apache/meta/main.yml будет содержать метаданные о роли, такие как зависимости:


---
dependencies: []
Шаг 8: Использование роли в плейбуке
Теперь вы можете использовать эту роль в вашем основном плейбуке. Создайте плейбук site.yml:

---
- name: Установка и настройка веб-сервера
  hosts: webservers
  become: yes

  roles:
    - apache
Шаг 9: Запуск плейбука
Запустите плейбук, чтобы применить роль:


ansible-playbook -i inventory site.yml
Замените inventory на путь к вашему инвентари-файлу, который определяет целевые хосты.